<footer class="site-footer">
  <h2><a href="mailto:info@jlnv.com.au">info@jlnv.com.au</a></h2>
  <h2><a href="https://github.com/John-Lak/JLNV_part1_project.git" target="_blank">Git Repository</a></h2>
  <h2><a href="https://votrnam.atlassian.net/jira/software/c/projects/NAM/boards/34/backlog?atlOrigin=eyJpIjoiODcwNWY1NDcyMTJmNDE0NGFmNDFkYjM0YzU4NWIxN2IiLCJwIjoiaiJ9" target="_blank">Jira Project</a></h2>
</footer>
</body>
</html>
